### ISSUE TITLE
Spec patterns did not match any files.

### ISSUE THREAD

**Issue by ARenfroe** [r3b/grunt-protractor-coverage#65]
$ node -v  v4.3.0
$ protractor --version  Version 3.0.0
# Gruntfile.js snippits

    protractor_coverage: {
                    options: {
                        keepAlive: true, // If false, the grunt process stops when the test fails.
                        noColor: false, // If true, protractor will not use colors in its output.
                        coverageDir: '<%= <app name>.instrumentedE2E %>'
                     },
                    local: {
                        options: {
                            configFile: "./test.old/protractor/conf.js"
                        }
                    }
                },

## Task runner

       return grunt.task.run([
                           'env:all',            // Set local config variables
                           'env:test',           // Set NODE_ENV=test
                           'express:dev',        // Start the server in dev mode
                            'clean:coverageE2E',
                            'copy:coverageE2E',
                            'instrument',
                            'protractor_coverage',
                            // 'protractor',
                            'makeReport'
                        ]);
                        
# Error

    /Users/<name>/<app name>/node_modules/protractor/node_modules/q/q.js:126
                        throw e;
                        ^
    
    Error: Spec patterns did not match any files.
        at Runner.run (/Users/<name>/<app name>/node_modules/protractor/lib/runner.js:249:11)
        at TaskRunner.run (/Users/<name>/<app name>/node_modules/protractor/lib/taskRunner.js:123:19)
        at createNextTaskRunner (/Users/<name>/<app name>/node_modules/protractor/lib/launcher.js:223:20)
        at /Users/<name>/<app name>/node_modules/protractor/lib/launcher.js:246:7
        at _fulfilled (/Users/<name>/<app name>/node_modules/protractor/node_modules/q/q.js:797:54)
        at self.promiseDispatch.done (/Users/<name>/<app name>/node_modules/protractor/node_modules/q/q.js:826:30)
        at Promise.promise.promiseDispatch (/Users/<name>/<app name>/node_modules/protractor/node_modules/q/q.js:759:13)
        at /Users/<name>/<app name>/node_modules/protractor/node_modules/q/q.js:573:44
        at flush (/Users/<name>/<app name>/node_modules/protractor/node_modules/q/q.js:108:17)
        at nextTickCallbackWith0Args (node.js:419:9)
        
        

# Config and Spec file

**new.spec.js**
    
    describe('it should laod the page',function () {
        it('should launch the page',function () {
            var loginURL = '<ourInternalURL>:3001/#/';
    
            browser.get(loginURL);
            browser.sleep(10000);
        });
    });
    
**conf.js**

    exports.config = {
        multiCapabilities: [{
            'browserName': 'chrome'
        }],
        //seleniumAddress: 'http://localhost:4444/wd/hub',
         specs: ['./new.spec.js'] // TODO comment out for now due to the new login page, as of 1/8/16
    };
 
When i swap our protractor_coverage with protractor in the task runner the tests execute fine but they are not running against the instrumented code so I dont get the reports. 

I have tried this with other conf and spec files that have been pulled from a repo upon npm install.  The spec and config files here are in the actual app hierarchy.  I'm not sure what the issue is.  Let me know if you need anything else.

**Comment by ARenfroe** [comment]
specs: ['./new.spec.js']
refactored to
specs['**/*.spec.js'] and everything works
